channels:
   - conda-forge
   - pytorch
   - anaconda
   - defaults
dependencies:
  - python=3.9
  - pip
  - wget
  - python-wget
  - joblib
  - pytorch==1.11.0
  - torchvision==0.12.0
  - cudatoolkit==11.3.1
  - ipython
  - ipykernel
  - pinocchio
  - rclone
  - pillow
  - ipywidgets
  - selenium
  - geckodriver
  - firefox
  - assimp
  - gxx_linux-64
  - ffmpeg
  - bzip2
  - git
  - cmake
  - numpy
  # extra for pym3t
  - opencv
  - compilers
  - scikit-build
  - mesa-libgl-devel-cos7-x86_64 
  - mesa-dri-drivers-cos7-x86_64 
  - libxcb
  - glew
  - glfw
  - librealsense
  - quaternion
  - pytest
  # extra for olt
  - setproctitle
  - pip:
      - pybullet
      - distributed
      - jinja2
      - pycollada
      - shapely
      - PyOpenGL
      - Cython
      - glumpy
      - scikit-video
      - scikit-image
      - scikit-learn
      - pywavefront
      - jupyter-client
      - jupyter-core
      - jupyter-server-proxy
      - jupyterlab
      - jupyterlab-server
      - meshcat
      - selenium
      - omegaconf
      - simplejson
      - line_profiler 
      # - opencv-python  # not compatible with conda opencv
      # - opencv-contrib-python  # not compatible with conda opencv
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - panda3d
      - joblib
      - xarray 
      - pandas
      - matplotlib
      - bokeh
      - plyfile 
      - trimesh 
      - ipdb 
      - panda3d-gltf
      - colorama
      - pyyaml
      - ipykernel
      - scipy
      - pypng
      - h5py 
      - seaborn
      - kornia 
      - pyarrow 
      - dt_apriltags 
      - open3d
      - structlog
      - imageio
      - progressbar
      - psutil
      - webdataset
      - roma 
      - torchgeometry
      - git+https://github.com/MedericFourmy/pym3t.git
      # extra for olt
      - thespian
      - pytest-benchmark
      - hypothesis

